name: GitHub Actions Demo
on: [push]
jobs:
  build-denpendence-and-images:
    runs-on: ubuntu-latest
    steps:

      - name: set-up-node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: pull-code-for-github
        run: |
          git clone -b F-DecoupleAws https://github.com/vmware/data-annotator-for-machine-learning.git
          git clone --branch=devops https://github.com/Kai-Qiao/data-annotator-for-machine-learning.git devops
          
      - name: config-sonar-project
        working-directory: ./devops/sonar
        run: | 
          python ./config_sonar_project.py -ProjectName github-actions-poc -ProjectKey github-actions-poc -OrgKey kai-qiao -QualityGateName angular-client-gate -QualityGateConditions ./quality_gates/angular-client.json -SonarToken ${{ secrets.SONAR_TOKEN }}

      - name: build-sonar-cloud
        uses: sonarsource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          projectBaseDir: ./data-annotator-for-machine-learning
          args: >
            -Dsonar.organization=kai-qiao
            -Dsonar.projectName=github-actions-poc
            -Dsonar.projectKey=github-actions-poc
            -Dsonar.sources=active-learning-service
            -Dsonar.test.exclusions=**/node_modules/**/*,**/models/**/*,**/downloadProject/**/*,**/logs/**/*,**/venv/**/*,**/__pycache__/**/*,*.md,*.txt,*.yml
            -Dsonar.verbose=false
            -Dsonar.c.file.suffixes=- 
            -Dsonar.cpp.file.suffixes=- 
            -Dsonar.objc.file.suffixes=-
            -Dsonar.typescript.lcov.reportPaths=-

          
