name: GitHub Actions Demo
on: [push]
jobs:
  build-denpendence-and-images:
    runs-on: ubuntu-latest
    steps:

      - name: set-up-node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: pull-code-for-github
        run: |
          git clone -b F-DecoupleAws https://github.com/vmware/data-annotator-for-machine-learning.git  

      - name: build-sonar-cloud
        uses: sonarsource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          SONAR_ORG: kai-qiao
          BRANCH: master
        with:
          projectBaseDir: ./data-annotator-for-machine-learning
          args: >
            -Dsonar.organization=${{ env.SONAR_ORG }}
            -Dsonar.projectName=data-annotator-for-machine-learning-poc
            -Dsonar.projectKey=data-annotator-for-machine-learning-poc
            -Dsonar.sources=active-learning-service
            -Dsonar.test.exclusions=**/node_modules/**/*,**/models/**/*,**/downloadProject/**/*,**/logs/**/*,**/venv/**/*,**/__pycache__/**/*,*.md,*.txt,*.yml

          
